[".config/nvim"]
type = "git-repo"
url = "https://github.com/NvChad/NvChad.git"
refreshPeriod = "168h"

[".local/share/zinit/zinit.git"]
type = "git-repo"
url = "https://github.com/zdharma-continuum/zinit.git"
refreshPeriod = "168h"