[".tmux/plugins/tpm"]
  type = "git-repo"
  url = "https://github.com/tmux-plugins/tpm"
  refreshPeriod = "168h"

[".local/share/nvim/site/pack/packer/start/packer.nvim"]
  type = "git-repo"
  url = "https://github.com/wbthomason/packer.nvim"
  refreshPeriod = "168h"
